const personajesFemeninos = [
    {
        nombre: "Rem",
        anime: "Re:Zero kara Hajimeru Isekai Seikatsu",
        imagen: "media/img/1.webp",
        video: "https://v.animethemes.moe/ReZero-OP2.webm",
        url: "https://rezero.fandom.com/wiki/Rem",
        descripcion: "La sirvienta más adorable y letal del multiverso. Puede derretir corazones y aplastar enemigos con la misma facilidad.",
        tituloVideo: "Opening - Paradisus-Paradoxum",
        episodio: "https://uqload.to/embed-0pbqlenlretw.html",
        trailer: "https://www.youtube.com/embed/Slz_rahWp6Y?si=00omRhwhcmPCpT7E",
        db: "https://anidb.net/anime/11370"
    },
    {
        nombre: "Megumin",
        anime: "Kono Subarashii Sekai ni Shukufuku wo!",
        imagen: "media/img/2.jpg",
        video: "https://v.animethemes.moe/KonosubaS2-OP1.webm",
        url: "https://konosuba.fandom.com/wiki/Megumin",
        descripcion: "Una hechicera obsesionada con la magia de explosiones. ¿Qué puede salir mal con una explosión diaria?",
        tituloVideo: "Opening - TOMORROW",
        episodio: "https://uqload.to/embed-k2dtfqsuo212.html",
        trailer: "https://www.youtube.com/embed/NU87y-38glA?si=6OmOVWpClF-UZJxm",
        db: "https://anidb.net/anime/11261"
    },
    {
        nombre: "Karyl",
        anime: "Princess Connect! Re:Dive",
        imagen: "media/img/3.jpg",
        video: "https://v.animethemes.moe/PrincessConnectReDiveS2-OP1-NCBD1080.webm",
        url: "https://princess-connect.fandom.com/wiki/Karyl",
        descripcion: "Una gata hechicera con un toque tsundere. Adora la comida tanto como sus hechizos.",
        tituloVideo: "Opening - Lost Princess",
        episodio: "https://uqload.to/embed-wdly1nijshkt.html",
        trailer: "https://www.youtube.com/embed/5NltMe8vX1o?si=nrHiUfHl7fr-z5gN",
        db: "https://anidb.net/anime/14690"
    },
    {
        nombre: "Aqua",
        anime: "Kono Subarashii Sekai ni Shukufuku wo!",
        imagen: "media/img/4.jpg",
        video: "https://v.animethemes.moe/Konosuba-OP1.webm",
        url: "https://konosuba.fandom.com/wiki/Aqua",
        descripcion: "La diosa más inútil y divertida que jamás conocerás. Con un ego del tamaño de su ineptitud divina, ilumina el mundo con sus desastres y desgracias.",
        tituloVideo: "Opening - Fantastic Dreamer",
        episodio: "https://uqload.to/embed-k2dtfqsuo212.html",
        trailer: "https://www.youtube.com/embed/NU87y-38glA?si=6OmOVWpClF-UZJxm",
        db: "https://anidb.net/anime/11261"
    },
    {
        nombre: "Mai Sakurajima",
        anime: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
        imagen: "media/img/5.jpg",
        video: "https://v.animethemes.moe/Aobuta-ED2-Lyrics.webm",
        url: "https://aobuta.fandom.com/wiki/Mai_Sakurajima",
        descripcion: "Una actriz famosa que a veces desaparece de la vista. No, no es un truco de magia.",
        tituloVideo: "Ending - Fukashigi no Karte",
        episodio: "https://uqload.to/embed-j8zekve1clds.html",
        trailer: "https://www.youtube.com/embed/o0TZj_d3Yfg?si=kIYeWw6Asncr4jHn",
        db: "https://anidb.net/anime/13900"
    },
    {
        nombre: "Roxy Migurdia",
        anime: "Mushoku Tensei: Isekai Ittara Honki Dasu",
        imagen: "media/img/6.webp",
        video: "https://v.animethemes.moe/MushokuTenseiS2-OP1-NCBD1080.webm",
        url: "https://mushokutensei.fandom.com/wiki/Roxy_Migurdia",
        descripcion: "Una hechicera pequeña pero poderosa, capaz de lanzar grandes hechizos y dar sabias lecciones. Su estatura no impide que su magia y su carácter sean gigantes.",
        tituloVideo: "Opening - Spiral",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9kb29kc3RyZWFtLmNvbS9lL3owcGF6bmpkOWtvdw==",
        trailer: "https://www.youtube.com/embed/k5VxfJpzy1Q?si=ixAwqhlNonIRQSLj",
        db: "https://anidb.net/anime/14758"
    },
    {
        nombre: "Sayu Ogiwara",
        anime: "Hige wo Soru. Soshite Joshikousei wo Hirou.",
        imagen: "media/img/7.png",
        video: "https://v.animethemes.moe/Higehiro-OP1-NCBD1080.webm",
        url: "https://higehiro.fandom.com/wiki/Sayu_Ogiwara",
        descripcion: "Una chica de secundaria con una historia complicada, pero siempre encuentra la forma de sonreír.",
        tituloVideo: "Opening - Omoide Shiritori",
        episodio: "https://www.burstcloud.co/embed/75e24f68292a55070f5d6fade5b84ec1dac14a1737a33cd8bb6fc2df996bffb2/Hige 1.mp4",
        trailer: "https://www.youtube.com/embed/nFljVg8xELU?si=tb8MhefgIb1paVS5",
        db: "https://anidb.net/anime/15332"
    },
    {
        nombre: "Kaguya Shinomiya",
        anime: "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
        imagen: "media/img/8.jpg",
        video: "https://v.animethemes.moe/KaguyaSamaWaKokurasetaiMovie-OP1.webm",
        url: "https://kaguyasama-wa-kokurasetai.fandom.com/wiki/Kaguya_Shinomiya",
        descripcion: "Una genio del amor y las estrategias. Con su inteligencia de supervillana y su torpeza emocional, convierte cada confesión en una guerra hilarante.",
        tituloVideo: "Opening - Love is Show",
        episodio: "https://uqload.to/embed-zui6b6gy8zwz.html",
        trailer: "https://www.youtube.com/embed/IwpJJiQkZzI?si=ZWDoixqx9agn3DmY",
        db: "https://anidb.net/anime/14111"
    },
    {
        nombre: "Chika Fujiwara",
        anime: "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
        imagen: "media/img/9.png",
        video: "https://v.animethemes.moe/KaguyaSamaWaKokurasetai-ED2-NCBD1080.webm",
        url: "https://kaguyasama-wa-kokurasetai.fandom.com/wiki/Chika_Fujiwara",
        descripcion: "El caos en forma de estudiante. Con su energía desbordante y ocurrencias locas, desarma cualquier plan serio con su torpeza encantadora.",
        tituloVideo: "Ending - Chikatto Chika Chika♡",
        episodio: "https://uqload.to/embed-zui6b6gy8zwz.html",
        trailer: "https://www.youtube.com/embed/IwpJJiQkZzI?si=ZWDoixqx9agn3DmY",
        db: "https://anidb.net/anime/14111"
    },
    {
        nombre: "Albedo",
        anime: "Overlord",
        imagen: "media/img/10.webp",
        video: "https://v.animethemes.moe/OverlordS3-OP1-NCBD1080.webm",
        url: "https://overlordmaruyama.fandom.com/wiki/Albedo",
        descripcion: "La guardiana más leal y enamorada de su señor, con un toque de obsesión divertida. Con su armadura imponente y sus celos desmedidos, combina el peligro y el humor en un solo paquete.",
        tituloVideo: "Opening - VORACITY",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly92b2Uuc3gvZS9yNnc4cXM5ZHBtcm0=",
        trailer: "https://www.youtube.com/embed/RuNAPPcjDr4?si=jGkNWkE-S7Fm58a4",
        db: "https://anidb.net/anime/10816"
    },
    {
        nombre: "Ai Ohto",
        anime: "Wonder Egg Priority",
        imagen: "media/img/11.jpg",
        video: "https://v.animethemes.moe/WonderEggPriority-OP1-NCBD1080.webm",
        url: "https://wonder-egg-priority.fandom.com/wiki/Ai_Ohto",
        descripcion: "Una joven aventurera en un mundo de sueños. Sus misterios son tan profundos como sus amigos.",
        tituloVideo: "Opening - Sudachi no Uta",
        episodio: "https://uqload.to/embed-9t0hsdc30jca.html",
        trailer: "https://www.youtube.com/embed/_TpTn3o-_Yk?si=cGsNA34LMR26vxcd",
        db: "https://anidb.net/anime/15772"
    },
    {
        nombre: "Megumi Kato",
        anime: "Saenai Heroine no Sodatekata",
        imagen: "media/img/12.jpg",
        video: "https://v.animethemes.moe/Saekano-OP1.webm",
        url: "https://saekano.fandom.com/wiki/Megumi_Kato",
        descripcion: "La heroína más normal del mundo, con una personalidad tan promedio, que logra robarse el protagonismo sin siquiera intentarlo.",
        tituloVideo: "Opening - Kimiiro Signal",
        episodio: "https://uqload.to/embed-ojjt3api4sq1.html",
        trailer: "https://www.youtube.com/embed/gsZb9-SRDDI?si=edLITLuXp7NiIsnZ",
        db: "https://anidb.net/anime/10538"
    },
    {
        nombre: "Yotsuba Nakano",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/13.webp",
        video: "https://v.animethemes.moe/GotoubunNoHanayomeSpecials-OP1.webm",
        url: "https://5hanayome.fandom.com/wiki/Yotsuba_Nakano",
        descripcion: "Atlética y enérgica, siempre está dispuesta a ayudarte con una sonrisa eterna. Su entusiasmo y espíritu deportivo la hacen la chispa del grupo, aunque a veces sus buenas intenciones causan más problemas de los que se resuelven.",
        tituloVideo: "Opening - Gotoubun no Mirai",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Nino Nakano",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/15.png",
        video: "https://v.animethemes.moe/GotoubunNoHanayomeSpecials-ED1.webm",
        url: "https://5hanayome.fandom.com/wiki/Nino_Nakano",
        descripcion: "Fuerte, independiente y tsundere, no te dejes engañar por su actitud dura. Su amor por la comida y su espíritu luchador la hacen tan memorable como temible.",
        tituloVideo: "Ending - Takaramono",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Ichika Nakano",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/16.webp",
        video: "https://v.animethemes.moe/GotoubunNoHanayomeS2-OP1-NCBD1080.webm",
        url: "https://5hanayome.fandom.com/wiki/Ichika_Nakano",
        descripcion: "Aspirante a actriz, con su astucia y encantos, es la hermana mayor que siempre tiene un plan... aunque no siempre sea el mejor.",
        tituloVideo: "Opening - Gotoubun no Katachi",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Miku Nakano",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/14.jpg",
        video: "https://v.animethemes.moe/EigaGotoubunNoHanayome-OP1.webm",
        url: "https://5hanayome.fandom.com/wiki/Miku_Nakano",
        descripcion: "La más reservada, pero con una pasión secreta. No subestimes su determinación.",
        tituloVideo: "Opening - Gotoubun no Kiseki",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Itsuki Nakano",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/17.jpg",
        video: "https://v.animethemes.moe/GotoubunNoHanayome-ED1.webm",
        url: "https://5hanayome.fandom.com/wiki/Itsuki_Nakano",
        descripcion: "La dedicada estudiante y amante de la comida, siempre tiene un snack a mano.",
        tituloVideo: "Ending - Sign",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Sumi Sakurasawa",
        anime: "Kanojo, Okarishimasu",
        imagen: "media/img/18.jpg",
        video: "https://v.animethemes.moe/Kanokari-OP1-NCBD1080.webm",
        url: "https://kanojo-okarishimasu.fandom.com/wiki/Sumi_Sakurasawa",
        descripcion: "La chica más tímida y adorable que podrías alquilar. Su torpeza encantadora y su esfuerzo por superar su timidez la hacen una explosión de ternura.",
        tituloVideo: "Opening - Centimeter",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzd4azB5OXlnMWF3bA==",
        trailer: "https://www.youtube.com/embed/jZFEtc3CKHs?si=bvpuU8On6oplXhtp",
        db: "https://anidb.net/anime/15299"
    },
    {
        nombre: "Frieren",
        anime: "Sousou no Frieren",
        imagen: "media/img/19.jpg",
        video: "https://v.animethemes.moe/SousouNoFrieren-OP1-NCBD1080.webm",
        url: "https://frieren.fandom.com/wiki/Frieren",
        descripcion: "Una elfa maga con un pasado heroico. Su calma y sabiduría son tan profundas como su longevidad.",
        tituloVideo: "Opening - Yuusha",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3Y2MzBvcmRoY2VhOQ==",
        trailer: "https://www.youtube.com/embed/qgQunxD0qCk?si=aq7CJ5LI4Xk7oU_y",
        db: "https://anidb.net/anime/17617"
    },
    {
        nombre: "Yukino Yukinoshita",
        anime: "Yahari Ore no Seishun Love Come wa Machigatteiru.",
        imagen: "media/img/20.jpg",
        video: "https://v.animethemes.moe/OreGairu-ED1.webm",
        url: "https://oregairu.fandom.com/wiki/Yukino_Yukinoshita",
        descripcion: "La reina del hielo con un cerebro tan afilado como su lengua. Bajo su fachada fría, hay un corazón que busca comprender y ser comprendido.",
        tituloVideo: "Ending - Hello Alone",
        episodio: "https://streamwish.to/e/5nslzgp4w6l3",
        trailer: "https://www.youtube.com/embed/u-bpwWPNEpE?si=OllU2RlCW-KgHM6b",
        db: "https://anidb.net/anime/9310"
    },
    {
        nombre: "Yui Yuigahama",
        anime: "Yahari Ore no Seishun Love Come wa Machigatteiru.",
        imagen: "media/img/21.jpeg",
        video: "https://v.animethemes.moe/OreGairuS2-OP1v2.webm",
        url: "https://oregairu.fandom.com/wiki/Yui_Yuigahama",
        descripcion: "La chispeante y alegre chica que siempre está ahí para sus amigos, su torpeza y buen humor son su firma personal.",
        tituloVideo: "Opening - Harumodoki",
        episodio: "https://streamwish.to/e/5nslzgp4w6l3",
        trailer: "https://www.youtube.com/embed/u-bpwWPNEpE?si=OllU2RlCW-KgHM6b",
        db: "https://anidb.net/anime/9310"
    },
    {
        nombre: "Iroha Isshiki",
        anime: "Yahari Ore no Seishun Love Come wa Machigatteiru.",
        imagen: "media/img/22.jpg",
        video: "https://v.animethemes.moe/OreGairuS3-OP1v4-NCBD1080.webm",
        url: "https://oregairu.fandom.com/wiki/Iroha_Isshiki",
        descripcion: "La astuta y encantadora presidenta del consejo estudiantil, con una sonrisa encantadora y un talento para manipular situaciones a su favor.",
        tituloVideo: "Opening - Megumi no Ame",
        episodio: "https://streamwish.to/e/5nslzgp4w6l3",
        trailer: "https://www.youtube.com/embed/u-bpwWPNEpE?si=OllU2RlCW-KgHM6b",
        db: "https://anidb.net/anime/9310"
    },
    {
        nombre: "Nezuko Kamado",
        anime: "Kimetsu no Yaiba",
        imagen: "media/img/23.jpg",
        video: "https://v.animethemes.moe/KimetsuNoYaiba-OP1-NCBD1080.webm",
        url: "https://kimetsu-no-yaiba.fandom.com/wiki/Nezuko_Kamado",
        descripcion: "La demonio más adorable y feroz que jamás verás. Con un bambú en la boca y una patada voladora lista, protege a su hermano con la ferocidad de un tigre y la dulzura de un conejito.",
        tituloVideo: "Opening - Gurenge",
        episodio: "https://uqload.to/embed-r3xsdxr53v7g.html",
        trailer: "https://www.youtube.com/embed/6vMuWuWlW4I?si=e-cAh8qSGOlwQDs5",
        db: "https://anidb.net/anime/14107"
    },
    {
        nombre: "Nanachi",
        anime: "Made in Abyss",
        imagen: "media/img/24.jpg",
        video: "https://v.animethemes.moe/MadeInAbyssS2-OP2-NCBD1080.webm",
        url: "https://madeinabyss.fandom.com/wiki/Nanachi",
        descripcion: "El peluche más sabio y sarcástico que jamás encontrarás en el Abismo. Con orejas esponjosas y una lengua afilada, combina conocimientos profundos con comentarios ingeniosos.",
        tituloVideo: "Opening - Katachi",
        episodio: "https://uqload.to/embed-wfqjkgc1omqt.html",
        trailer: "https://www.youtube.com/embed/AQbaZeby2zA?si=sZcU7mLDvREjk8si",
        db: "https://anidb.net/anime/12681"
    },
    {
        nombre: "Shinobu Oshino",
        anime: "Bakemonogatari",
        imagen: "media/img/25.jpg",
        video: "https://v.animethemes.moe/Bakemonogatari-ED1.webm",
        url: "https://bakemonogatari.fandom.com/wiki/Shinobu_Oshino",
        descripcion: "Una vampira con un gusto por las donas. Su apariencia es tan engañosa como su edad.",
        tituloVideo: "Ending - Kimi no Shiranai Monogatari",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2NrZjZiZ3hhNzliZA==",
        trailer: "https://www.youtube.com/embed/X63_YYZjKxA?si=A2iys5fMm6nZncof",
        db: "https://anidb.net/anime/6327"
    },
    {
        nombre: "Mayuri Shiina",
        anime: "Steins;Gate",
        imagen: "media/img/26.jpg",
        video: "https://v.animethemes.moe/SteinsGate-OP1v2.webm",
        url: "https://steins-gate.fandom.com/wiki/Mayuri_Shiina",
        descripcion: "La reina de los 'tuturuu~' y los abrazos, es la amiga de la infancia que siempre trae una sonrisa.",
        tituloVideo: "Opening - Hacking to the Gate",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3pvNHl5MWEwOG9weA==",
        trailer: "https://www.youtube.com/embed/27OZc-ku6is?si=gWUJP6ezf2X44Fl4",
        db: "https://anidb.net/anime/7729"
    },
    {
        nombre: "Kurisu Makise",
        anime: "Steins;Gate",
        imagen: "media/img/27.png",
        video: "https://v.animethemes.moe/SteinsGateZero-OP1-NCBD1080Lyrics.webm",
        url: "https://steins-gate.fandom.com/wiki/Kurisu_Makise",
        descripcion: "La tsundere científica prodigio con un coeficiente intelectual deslumbrante y una debilidad por las Dr Pepper.",
        tituloVideo: "Opening - Fatima",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3pvNHl5MWEwOG9weA==",
        trailer: "https://www.youtube.com/embed/27OZc-ku6is?si=gWUJP6ezf2X44Fl4",
        db: "https://anidb.net/anime/7729"
    },
    {
        nombre: "Airi Katagiri",
        anime: "Boku dake ga Inai Machi",
        imagen: "media/img/28.jpg",
        video: "https://v.animethemes.moe/BokuDakeGaInaiMachi-OP1.webm",
        url: "https://bokudakegainaimachi.fandom.com/wiki/Airi_Katagiri",
        descripcion: "Una chica trabajadora con un fuerte sentido de justicia. Su sonrisa es tan cálida como su corazón.",
        tituloVideo: "Opening - Re:Re:",
        episodio: "https://uqload.to/embed-64yjnq1dymp9.html",
        trailer: "https://www.youtube.com/embed/TZzMOC-4k6M?si=2u9ZFP4zjV5xBHVz",
        db: "https://anidb.net/anime/11292"
    },
    {
        nombre: "Kagari",
        anime: "Rewrite",
        imagen: "media/img/29.jpg",
        video: "https://v.animethemes.moe/Rewrite-OP1.webm",
        url: "https://rewrite.fandom.com/wiki/Kagari",
        descripcion: "Una misteriosa chica con un vínculo con la naturaleza. Su presencia es tan enigmática como su identidad.",
        tituloVideo: "Opening - Philosophyz",
        episodio: "https://uqload.to/embed-acljj3rie4ex.html",
        trailer: "https://www.youtube.com/embed/zACG02alQO0?si=2XU9vT4KoGmO_W1f",
        db: "https://anidb.net/anime/11643"
    },
    {
        nombre: "Rinne Ohara",
        anime: "ISLAND",
        imagen: "media/img/30.jpg",
        video: "https://v.animethemes.moe/Island-OP1-NCBD1080.webm",
        url: "https://frontwing-island.fandom.com/wiki/Rinne_Ohara",
        descripcion: "Una joven aislada en una isla misteriosa. Con su afición por las almohadas y su tendencia a dormirse en los lugares más extraños, siempre está lista para lanzar un comentario sarcástico o una patada sorpresa.",
        tituloVideo: "Opening - Eien no Hitotsu",
        episodio: "https://uqload.to/embed-0t1yqddrr9gf.html",
        trailer: "https://www.youtube.com/embed/-bj9Slfi3YY?si=Yi9prDhWJOvRYtwL",
        db: "https://anidb.net/anime/12020"
    },
    {
        nombre: "Chisato Nishikigi",
        anime: "Lycoris Recoil",
        imagen: "media/img/31.jpg",
        video: "https://v.animethemes.moe/LycorisRecoil-OP1-NCBD1080.webm",
        url: "https://lycoris-recoil.fandom.com/wiki/Chisato_Nishikigi",
        descripcion: "Una agente de élite alegre y despreocupada, con una puntería impecable y una sonrisa que nunca desaparece. Su amor por el té y las travesuras la hace tan encantadora como letal.",
        tituloVideo: "Opening - ALIVE",
        episodio: "https://uqload.to/embed-elhnzb5g9y57.html",
        trailer: "https://www.youtube.com/embed/rvu_s7Vp4KE?si=RCPcuWmIIJC8Z25m",
        db: "https://anidb.net/anime/17097"
    },
    {
        nombre: "Takina Inoue",
        anime: "Lycoris Recoil",
        imagen: "media/img/32.png",
        video: "https://v.animethemes.moe/LycorisRecoil-ED1-NCBD1080.webm",
        url: "https://lycoris-recoil.fandom.com/wiki/Takina_Inoue",
        descripcion: "Una agente seria y dedicada, con una habilidad increíble para la acción y una paciencia infinita para las ocurrencias de su amiga.",
        tituloVideo: "Ending - Hana no Tou",
        episodio: "https://uqload.to/embed-elhnzb5g9y57.html",
        trailer: "https://www.youtube.com/embed/rvu_s7Vp4KE?si=RCPcuWmIIJC8Z25m",
        db: "https://anidb.net/anime/17097"
    },
    {
        nombre: "Takagi",
        anime: "Karakai Jouzu no Takagi-san",
        imagen: "media/img/33.webp",
        video: "https://v.animethemes.moe/Takagi3S3-OP1-NCBD1080.webm",
        url: "https://karakai-jouzu-no-takagi-san.fandom.com/wiki/Takagi",
        descripcion: "La maestra indiscutible del arte de las bromas. Con una sonrisa traviesa y una mente aguda, siempre tiene una broma lista para hacerte sonrojar.",
        tituloVideo: "Opening - Massugu",
        episodio: "https://uqload.to/embed-tvpvb9wh1193.html",
        trailer: "https://www.youtube.com/embed/g4VJra3sLMg?si=JozqgopuedckxXGt",
        db: "https://anidb.net/anime/13270"
    },
    {
        nombre: "Vladilena Milizé",
        anime: "86: Eighty Six",
        imagen: "media/img/34.jpg",
        video: "https://v.animethemes.moe/86-OP1-NCBD1080.webm",
        url: "https://86-eighty-six.fandom.com/wiki/Vladilena_Miliz%C3%A9",
        descripcion: "Una oficial militar con un corazón de oro. Su valentía y compasión la hacen única.",
        tituloVideo: "Opening - 3-pun 29-byou",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2hubHMwejVzYXZsYg==",
        trailer: "https://www.youtube.com/embed/VSdS29SDvn4?si=ytsE70xVkY4rkWOW",
        db: "https://anidb.net/anime/15441"
    },
    {
        nombre: "Lum",
        anime: "Urusei Yatsura",
        imagen: "media/img/35.jpg",
        video: "https://v.animethemes.moe/UruseiYatsura2022-OP2.webm",
        url: "https://uruseiyatsura.fandom.com/wiki/Lum",
        descripcion: "La alienígena más electrizante y encantadora del universo. Siempre está persiguiendo a su 'darling' con una mezcla de amor y truenos.",
        tituloVideo: "Opening - Ai wa Namuchu feat. asmi, Surii",
        episodio: "https://uqload.to/embed-1en8i4e758bm.html",
        trailer: "https://www.youtube.com/embed/LXlFsAI3sYQ?si=bUzppOq_26VKcp9l",
        db: "https://anidb.net/anime/17096"
    },
    {
        nombre: "Raphtalia",
        anime: "Tate no Yuusha no Nariagari",
        imagen: "media/img/36.png",
        video: "https://v.animethemes.moe/ShieldHero-OP1-NCBD1080.webm",
        url: "https://shield-hero.fandom.com/wiki/Raphtalia",
        descripcion: "Una chica tan tierna como letal, con sus adorables orejas y cola de mapache, y su lealtad inquebrantable, es la combinación perfecta de dulzura y valentía.",
        tituloVideo: "Opening - RISE",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzQ3N21ncHB0YTZsZw==",
        trailer: "https://www.youtube.com/embed/VKYmpq-V3Rs?si=juZWOS-NbcSI6LYF",
        db: "https://anidb.net/anime/13246"
    },
    {
        nombre: "Yuuko Yoshida",
        anime: "Machikado Mazoku",
        imagen: "media/img/37.jpg",
        video: "https://v.animethemes.moe/MachikadoMazoku-OP1-NCBD1080.webm",
        url: "https://machikado-mazoku.fandom.com/wiki/Yuko_Yoshida",
        descripcion: "La demonio más inofensiva y torpe que puedas encontrar. Con su cuerno pequeño y su falta de habilidades malignas, lucha contra su destino con más entusiasmo que éxito.",
        tituloVideo: "Opening - Machikado Tangent",
        episodio: "https://uqload.to/embed-fgwmy0k67qy2.html",
        trailer: "https://www.youtube.com/embed/ESNhhG3QQBQ?si=rISp4igl2nclxAQ7",
        db: "https://anidb.net/anime/14630"
    },
    {
        nombre: "Kei Karuizawa",
        anime: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
        imagen: "media/img/38.jpg",
        video: "https://v.animethemes.moe/YoukosoZitsuS3-OP1v2.webm",
        url: "https://you-zitsu.fandom.com/wiki/Kei_Karuizawa",
        descripcion: "Una chica inteligente y calculadora con un lado vulnerable. Siempre en el centro del drama y las intrigas, maneja los rumores y las relaciones como una reina.",
        tituloVideo: "Opening - Minor Piece",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3FxMWJ2NjZ4NjFzMA==",
        trailer: "https://www.youtube.com/embed/iYsx6w5PNno?si=QlHRPM6H7WfzH1dW",
        db: "https://anidb.net/anime/13153"
    },
    {
        nombre: "Emilico",
        anime: "Shadows House",
        imagen: "media/img/39.jpg",
        video: "https://v.animethemes.moe/ShadowsHouseS2-OP1.webm",
        url: "https://shadows-house.fandom.com/wiki/Emilico",
        descripcion: "Una muñeca viviente con un espíritu luminoso. Su curiosidad y amabilidad son contagiosas.",
        tituloVideo: "Opening - Shall We Dance?",
        episodio: "https://uqload.to/embed-54wm1kcgklpv.html",
        trailer: "https://www.youtube.com/embed/dUlo9T1UQVo?si=Ga1o6xSjNErkS7LQ",
        db: "https://anidb.net/anime/15779"
    },
    {
        nombre: "Ai Hoshino",
        anime: "[Oshi no Ko]",
        imagen: "media/img/40.jpg",
        video: "https://v.animethemes.moe/OshiNoKo-OP1-NCBD1080.webm",
        url: "https://oshinoko.fandom.com/wiki/Ai_Hoshino",
        descripcion: "Una idol cuya sonrisa puede derretir icebergs y cuyo carisma brilla como una supernova.",
        tituloVideo: "Opening - Idol",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzQ3NG9zNjNjd3Yybg==",
        trailer: "https://www.youtube.com/embed/gKWEUJ4r5do?si=zqAPIQ55SnRCLbWT",
        db: "https://anidb.net/anime/17449"
    },
    {
        nombre: "Emilia",
        anime: "Re:Zero kara Hajimeru Isekai Seikatsu",
        imagen: "media/img/47.jpg",
        video: "https://v.animethemes.moe/ReZeroS2Part2-OP1-NCBD1080.webm",
        url: "https://rezero.fandom.com/wiki/Emilia",
        descripcion: "La semielfa más dulce y despistada del reino. Con su amor por los espíritus y su tendencia a meterse en líos, conquista corazones con su inocencia y encanto.",
        tituloVideo: "Opening - Long shot",
        episodio: "https://uqload.to/embed-0pbqlenlretw.html",
        trailer: "https://www.youtube.com/embed/Slz_rahWp6Y?si=00omRhwhcmPCpT7E",
        db: "https://anidb.net/anime/11370"
    },
    {
        nombre: "Riko",
        anime: "Made in Abyss",
        imagen: "media/img/55.jpg",
        video: "https://v.animethemes.moe/MadeInAbyss-OP2-NCBD1080.webm",
        url: "https://madeinabyss.fandom.com/wiki/Riko",
        descripcion: "La exploradora más valiente y curiosa, siempre lista para adentrarse en lo desconocido, incluso si eso significa desafiar monstruos gigantes y maldiciones aterradoras.",
        tituloVideo: "Opening - Deep in Abyss",
        episodio: "https://uqload.to/embed-wfqjkgc1omqt.html",
        trailer: "https://www.youtube.com/embed/AQbaZeby2zA?si=sZcU7mLDvREjk8si",
        db: "https://anidb.net/anime/12681"
    },
    {
        nombre: "Satania",
        anime: "Gabriel Dropout",
        imagen: "media/img/66.jpeg",
        video: "https://v.animethemes.moe/GabrielDropout-OP1.webm",
        url: "https://gabdro.fandom.com/wiki/Satanichia_Kurumizawa_Mcdowell",
        descripcion: "La demonio más torpe y presumida del infierno. Con su ambición de ser la villana más temida y su habilidad para meterse en problemas, su vida es un desfile de situaciones cómicas y desastres autoproclamados.",
        tituloVideo: "Opening - Gabriel Drop Kick",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzhlY2w4azBuaXgxcg==",
        trailer: "https://www.youtube.com/embed/4eADGP3b9j0?si=Iq2ewjlAuvx3WFZe",
        db: "https://anidb.net/anime/12290"
    },
    {
        nombre: "Yuki Takeya",
        anime: "Gakkou Gurashi!",
        imagen: "media/img/67.jpg",
        video: "https://v.animethemes.moe/GakkouGurashi-OP1.webm",
        url: "https://gakkou-gurashi.fandom.com/wiki/Yuki_Takeya",
        descripcion: "La estudiante más alegre y despreocupada, con una imaginación desbordante y una habilidad para convertir el apocalipsis en un juego. Su vida es una mezcla hilarante de optimismo y supervivencia.",
        tituloVideo: "Opening - Friend Shitai",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly93d3cubXA0dXBsb2FkLmNvbS9lbWJlZC1iazJ6ZDU3OTRuM3EuaHRtbA==",
        trailer: "https://www.youtube.com/embed/mYyu0yys5Ks?si=yTrdX6VZjThUSl4X",
        db: "https://anidb.net/anime/10697"
    },
    {
        nombre: "Rory Mercury",
        anime: "Gate: Jieitai Kanochi nite, Kaku Tatakaeri",
        imagen: "media/img/68.jpg",
        video: "https://v.animethemes.moe/Gate-OP1.webm",
        url: "https://gate.fandom.com/wiki/Rory_Mercury",
        descripcion: "Una semidiosa gótica con una hacha tan grande como su personalidad. Con su apariencia de niña y su edad milenaria, adora el caos y el combate tanto como un buen chisme.",
        tituloVideo: "Opening - GATE: Sore wa Akatsuki no you ni",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2c0dnZ6aW96a2dxdQ==",
        trailer: "https://www.youtube.com/embed/IulCg2hnu54?si=7cv2JNeIvMfra4X9",
        db: "https://anidb.net/anime/10982"
    },
    {
        nombre: "Satō Matsuzaka",
        anime: "Happy Sugar Life",
        imagen: "media/img/69.jpeg",
        video: "https://v.animethemes.moe/HappySugarLife-OP1-NCBD1080.webm",
        url: "https://happy-sugar-life.fandom.com/wiki/Sat%C5%8D_Matsuzaka",
        descripcion: "La chica más dulce del vecindario... y también la más peligrosa. Con su sonrisa encantadora y su amor inquebrantable, es como una mezcla de algodón de azúcar y dinamita.",
        tituloVideo: "Opening - One Room Sugar Life",
        episodio: "https://uqload.to/embed-vezedd2vwftn.html",
        trailer: "https://www.youtube.com/embed/hLZENGd_GjA?si=maP8DXWLyfJwC2_R",
        db: "https://anidb.net/anime/13944"
    },
    {
        nombre: "Yui Furukawa",
        anime: "Ushinawareta Mirai o Motomete",
        imagen: "media/img/71.jpeg",
        video: "https://v.animethemes.moe/UshinawaretaMiraiWoMotomete-OP1.webm",
        url: "https://waremete.fandom.com/wiki/Yui_Furukawa",
        descripcion: "Una chica misteriosa con un toque futurista. Siempre parece saber algo que tú no sabes, y su presencia garantiza aventuras llenas de sorpresas y diversión.",
        tituloVideo: "Opening - Le jour",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly93d3cubXA0dXBsb2FkLmNvbS9lbWJlZC1oN2ZkMzZkY2k4cWMuaHRtbA==",
        trailer: "https://www.youtube.com/embed/mghBYKjGngQ?si=-RNSFuNgr_zOISar",
        db: "https://anidb.net/anime/10372"
    },
    {
        nombre: "Urara Shiraishi",
        anime: "Yamada-kun to Nananin no Majo",
        imagen: "media/img/72.jpg",
        video: "https://v.animethemes.moe/YamadaKun-ED1.webm",
        url: "https://nananinnomajo.fandom.com/wiki/Urara_Shiraishi",
        descripcion: "La cerebrito del colegio que termina siendo la compañera del protagonista en situaciones mágicas y caóticas. Inteligente y serena, se ve arrastrada a las aventuras más disparatadas, demostrando que incluso las mentes brillantes pueden acabar en situaciones cómicamente absurdas.",
        tituloVideo: "Ending - CANDY MAGIC",
        episodio: "https://uqload.to/embed-r5kw1ujs49z7.html",
        trailer: "https://www.youtube.com/embed/vDOknfJIUu4?si=Ff-Z4_fXpCnLkiR_",
        db: "https://anidb.net/anime/10955"
    },
    {
        nombre: "Alice Zuberg",
        anime: "Sword Art Online",
        imagen: "media/img/75.png",
        video: "https://v.animethemes.moe/SwordArtOnlineAlicizationS2-OP1-NCBD1080.webm",
        url: "https://swordartonline.fandom.com/wiki/Alice_Zuberg",
        descripcion: "Una valiente caballera con un toque de ternura. Con su armadura dorada y su espada resplandeciente, está lista para salvar el día y lucir fabulosa mientras lo hace.",
        tituloVideo: "Opening - Resolution",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL250MXVobTBkMWg0eg==",
        trailer: "https://www.youtube.com/embed/aPP_Ut9Wqlg?si=ZGiQPnYb412uekRX",
        db: "https://anidb.net/anime/8692"
    },
    {
        nombre: "Darkness",
        anime: "Kono Subarashii Sekai ni Shukufuku wo!",
        imagen: "media/img/77.webp",
        video: "https://v.animethemes.moe/Konosuba-ED1.webm",
        url: "https://konosuba.fandom.com/wiki/Darkness",
        descripcion: "La valiente pero algo masoquista caballera. Le encanta lanzarse a la batalla... y recibir golpes. Imagina a una guerrera superpoderosa que disfruta los desafíos tanto como un perrito disfruta las caricias.",
        tituloVideo: "Ending - Chiisana Boukensha",
        episodio: "https://uqload.to/embed-k2dtfqsuo212.html",
        trailer: "https://www.youtube.com/embed/NU87y-38glA?si=6OmOVWpClF-UZJxm",
        db: "https://anidb.net/anime/11261"
    },
    {
        nombre: "Fern",
        anime: "Sousou no Frieren",
        imagen: "media/img/78.jpeg",
        video: "https://v.animethemes.moe/SousouNoFrieren-ED1-NCBD1080.webm",
        url: "https://frieren.fandom.com/wiki/Fern",
        descripcion: "Una maga joven y seria, pero con el corazón de una abuelita preocupada. Siempre está lista para lanzar hechizos poderosos, aunque a veces parece más preocupada por tener sus libros de magia bien organizados.",
        tituloVideo: "Ending - Anytime Anywhere",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3Y2MzBvcmRoY2VhOQ==",
        trailer: "https://www.youtube.com/embed/qgQunxD0qCk?si=aq7CJ5LI4Xk7oU_y",
        db: "https://anidb.net/anime/17617"
    },
    {
        nombre: "Nadeko Sengoku",
        anime: "Bakemonogatari",
        imagen: "media/img/81.jpg",
        video: "https://v.animethemes.moe/Bakemonogatari-OP4v2.webm",
        url: "https://bakemonogatari.fandom.com/wiki/Nadeko_Sengoku",
        descripcion: "La chica tímida y dulce que parece un ángel, pero tiene un lado serpenteante. Es como una gominola encantadora que puede volverse picante de repente.",
        tituloVideo: "Opening - Ren'ai Circulation",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2NrZjZiZ3hhNzliZA==",
        trailer: "https://www.youtube.com/embed/X63_YYZjKxA?si=A2iys5fMm6nZncof",
        db: "https://anidb.net/anime/6327"
    },
    {
        nombre: "Mayoi Hachikuji",
        anime: "Bakemonogatari",
        imagen: "media/img/82.jpg",
        video: "https://v.animethemes.moe/Bakemonogatari-OP2.webm",
        url: "https://bakemonogatari.fandom.com/wiki/Mayoi_Hachikuji",
        descripcion: "La pequeña fantasma perdida con una gran mochila y un aún más grande sentido del humor. Siempre está lista con una broma y una sonrisa, haciendo de cada encuentro una divertida aventura.",
        tituloVideo: "Opening - Kaerimichi",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2NrZjZiZ3hhNzliZA==",
        trailer: "https://www.youtube.com/embed/X63_YYZjKxA?si=A2iys5fMm6nZncof",
        db: "https://anidb.net/anime/6327"
    },
];

export { personajesFemeninos };