const personajesMasculinos = [
    {
        nombre: "Senkuu Ishigami",
        anime: "Dr. STONE",
        imagen: "media/img/41.jpg",
        video: "https://v.animethemes.moe/DrStone-OP1-NCBD1080.webm",
        url: "https://dr-stone.fandom.com/wiki/Senku_Ishigami",
        descripcion: "Un científico brillante con un peinado peculiar. Con un cerebro de 10 mil millones de IQ y una obsesión por la ciencia, puede reconstruir la civilización con un poco de ácido sulfúrico y mucha determinación.",
        tituloVideo: "Opening - Good Morning World!",
        episodio: "https://mega.nz/embed/P5Z1xIJB#kBZ_wU2VwKnR-vnE00YUatm0ubXoT6bvLNQJvEzTDxE",
        trailer: "https://www.youtube.com/embed/7YZzYeBartM?si=BJo1E-TRbA20xt0i",
        db: "https://anidb.net/anime/14491"
    },
    {
        nombre: "Rintarou Okabe",
        anime: "Steins;Gate",
        imagen: "media/img/42.jpg",
        video: "https://v.animethemes.moe/SteinsGate-ED1.webm",
        url: "https://steins-gate.fandom.com/wiki/Rintaro_Okabe",
        descripcion: "El autoproclamado 'científico loco' con un amor por los gadgets, una risa maníaca y una imaginación hiperactiva. ",
        tituloVideo: "Ending - Toki Tsukasadoru Juuni no Meiyaku",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3pvNHl5MWEwOG9weA==",
        trailer: "https://www.youtube.com/embed/27OZc-ku6is?si=gWUJP6ezf2X44Fl4",
        db: "https://anidb.net/anime/7729"
    },
    {
        nombre: "Fuutarou Uesugi",
        anime: "Go-toubun no Hanayome",
        imagen: "media/img/43.jpg",
        video: "https://v.animethemes.moe/GotoubunNoHanayome-OP1-NCBD1080.webm",
        url: "https://5hanayome.fandom.com/wiki/Futaro_Uesugi",
        descripcion: "El genio estudioso que se convierte en tutor de cinco quintillizas, equilibrando sus problemas financieros con las locuras de su nuevo trabajo.",
        tituloVideo: "Opening - Gotoubun no Kimochi",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2ZvN3c3enh0MTFhYw==",
        trailer: "https://www.youtube.com/embed/pCwfEB6PbFk?si=SfbFT6UQ7mIG8wm7",
        db: "https://anidb.net/anime/14247"
    },
    {
        nombre: "Hachiman Hikigaya",
        anime: "Yahari Ore no Seishun Love Come wa Machigatteiru.",
        imagen: "media/img/44.jpg",
        video: "https://v.animethemes.moe/OreGairuS2-ED1.webm",
        url: "https://oregairu.fandom.com/wiki/Hachiman_Hikigaya",
        descripcion: "El maestro del cinismo y el sarcasmo, con una visión pesimista de la vida que es tan afilada como su lengua. Prefiere la soledad y los libros a la interacción social.",
        tituloVideo: "Ending - Everyday World",
        episodio: "https://streamwish.to/e/5nslzgp4w6l3",
        trailer: "https://www.youtube.com/embed/u-bpwWPNEpE?si=OllU2RlCW-KgHM6b",
        db: "https://anidb.net/anime/9310"
    },
    {
        nombre: "Natsuki Subaru",
        anime: "Re:Zero kara Hajimeru Isekai Seikatsu",
        imagen: "media/img/45.webp",
        video: "https://v.animethemes.moe/ReZero-OP1.webm",
        url: "https://rezero.fandom.com/wiki/Natsuki_Subaru",
        descripcion: "El héroe más desafortunado y cabezota, reviviendo más veces que un gato con nueve vidas. Enfrenta cada desastre con humor y determinación otaku.",
        tituloVideo: "Opening - Redo",
        episodio: "https://uqload.to/embed-0pbqlenlretw.html",
        trailer: "https://www.youtube.com/embed/Slz_rahWp6Y?si=00omRhwhcmPCpT7E",
        db: "https://anidb.net/anime/11370"
    },
    {
        nombre: "Kazuma Satou",
        anime: "Kono Subarashii Sekai ni Shukufuku wo!",
        imagen: "media/img/46.jpg",
        video: "https://v.animethemes.moe/KonosubaS3-OP1.webm",
        url: "https://konosuba.fandom.com/wiki/Kazuma_Satou",
        descripcion: "El aventurero más desafortunado y sarcástico. Equipado con habilidades mediocres y un grupo de compañeros desastrosos, su vida en otro mundo es un caos hilarante.",
        tituloVideo: "Opening - Growing Up",
        episodio: "https://uqload.to/embed-k2dtfqsuo212.html",
        trailer: "https://www.youtube.com/embed/NU87y-38glA?si=6OmOVWpClF-UZJxm",
        db: "https://anidb.net/anime/11261"
    },
    {
        nombre: "Sakuta Azusagawa",
        anime: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
        imagen: "media/img/48.jpg",
        video: "https://v.animethemes.moe/Aobuta-OP1-Lyrics.webm",
        url: "https://aobuta.fandom.com/wiki/Sakuta_Azusagawa",
        descripcion: "El maestro del sarcasmo y el cinismo con un corazón de oro. Entre resolver misterios sobrenaturales y manejar su vida amorosa con una senpai vestida de conejita, su vida nunca es aburrida.",
        tituloVideo: "Opening - Kimi no Sei",
        episodio: "https://uqload.to/embed-j8zekve1clds.html",
        trailer: "https://www.youtube.com/embed/o0TZj_d3Yfg?si=kIYeWw6Asncr4jHn",
        db: "https://anidb.net/anime/13900"
    },
    {
        nombre: "Rudeus Greyrat",
        anime: "Mushoku Tensei: Isekai Ittara Honki Dasu",
        imagen: "media/img/49.jpg",
        video: "https://v.animethemes.moe/MushokuTensei-OP1-NCBD1080.webm",
        url: "https://mushokutensei.fandom.com/wiki/Rudeus_Greyrat",
        descripcion: "Un mago prodigio con la mente de un adulto y el cuerpo de un niño. Reencarnado con todos sus recuerdos, mezcla sabiduría con travesuras infantiles.",
        tituloVideo: "Opening - Tabibito no Uta",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9kb29kc3RyZWFtLmNvbS9lL3owcGF6bmpkOWtvdw==",
        trailer: "https://www.youtube.com/embed/k5VxfJpzy1Q?si=ixAwqhlNonIRQSLj",
        db: "https://anidb.net/anime/14758"
    },
    {
        nombre: "Miyuki Shirogane",
        anime: "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
        imagen: "media/img/50.jpg",
        video: "https://v.animethemes.moe/KaguyaSamaWaKokurasetai-OP1-NCBD1080.webm",
        url: "https://kaguyasama-wa-kokurasetai.fandom.com/wiki/Miyuki_Shirogane",
        descripcion: "El presidente del consejo estudiantil, tiene una ética de trabajo tan extrema que necesita tutoriales de YouTube para relajarse.",
        tituloVideo: "Opening - Love Dramatic feat. Rikka Ihara",
        episodio: "https://uqload.to/embed-zui6b6gy8zwz.html",
        trailer: "https://www.youtube.com/embed/IwpJJiQkZzI?si=ZWDoixqx9agn3DmY",
        db: "https://anidb.net/anime/14111"
    },
    {
        nombre: "Ainz Ooal Gown",
        anime: "Overlord",
        imagen: "media/img/51.jpg",
        video: "https://v.animethemes.moe/OverlordS4-OP1-NCBD1080.webm",
        url: "https://overlordmaruyama.fandom.com/wiki/Ainz_Ooal_Gown",
        descripcion: "El señor supremo de los no-muertos con una agenda tan ocupada conquistando el mundo como intentando recordar su nombre original.",
        tituloVideo: "Opening - HOLLOW HUNGER",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly92b2Uuc3gvZS9yNnc4cXM5ZHBtcm0=",
        trailer: "https://www.youtube.com/embed/RuNAPPcjDr4?si=jGkNWkE-S7Fm58a4",
        db: "https://anidb.net/anime/10816"
    },
    {
        nombre: "Tomoya Aki",
        anime: "Saenai Heroine no Sodatekata",
        imagen: "media/img/52.jpg",
        video: "https://v.animethemes.moe/SaekanoS2EpZero-OP1.webm",
        url: "https://saekano.fandom.com/wiki/Tomoya_Aki",
        descripcion: "El maestro del harem otaku con una misión: crear la heroína perfecta para su juego. Entre momentos dramáticos y escenas románticas inventadas, su vida es un desafío cómico de amor, amistad y... crear la novela visual definitiva.",
        tituloVideo: "Opening - Stella Breeze",
        episodio: "https://uqload.to/embed-ojjt3api4sq1.html",
        trailer: "https://www.youtube.com/embed/gsZb9-SRDDI?si=edLITLuXp7NiIsnZ",
        db: "https://anidb.net/anime/10538"
    },
    {
        nombre: "Tanjiro Kamado",
        anime: "Kimetsu no Yaiba",
        imagen: "media/img/53.jpg",
        video: "https://v.animethemes.moe/KimetsuNoYaiba-ED2-Lyrics.webm",
        url: "https://kimetsu-no-yaiba.fandom.com/wiki/Tanjiro_Kamado",
        descripcion: "El espadachín más amable y cabezota con un olfato increíblemente agudo. Entre decapitar demonios y cuidar de su hermana, siempre encuentra tiempo para ser increíblemente educado.",
        tituloVideo: "Ending - Kamado Tanjiro no Uta",
        episodio: "https://uqload.to/embed-r3xsdxr53v7g.html",
        trailer: "https://www.youtube.com/embed/6vMuWuWlW4I?si=e-cAh8qSGOlwQDs5",
        db: "https://anidb.net/anime/14107"
    },
    {
        nombre: "Reg",
        anime: "Made in Abyss",
        imagen: "media/img/54.jpeg",
        video: "https://v.animethemes.moe/MadeInAbyss-OP1.webm",
        url: "https://madeinabyss.fandom.com/wiki/Reg",
        descripcion: "El robot más adorable y confundido del Abismo. Con brazos extensibles y un cañón láser potente, sufre de amnesia pero nunca pierde su sentido del deber ni su encanto infantil.",
        tituloVideo: "Opening - Underground River",
        episodio: "https://uqload.to/embed-wfqjkgc1omqt.html",
        trailer: "https://www.youtube.com/embed/AQbaZeby2zA?si=sZcU7mLDvREjk8si",
        db: "https://anidb.net/anime/12681"
    },
    {
        nombre: "Koyomi Araragi",
        anime: "Bakemonogatari",
        imagen: "media/img/56.jpeg",
        video: "https://v.animethemes.moe/Bakemonogatari-OP1.webm",
        url: "https://bakemonogatari.fandom.com/wiki/Koyomi_Araragi",
        descripcion: "El estudiante más sarcástico y desafortunado con una extraña afinidad por lo sobrenatural. Entre salvar a chicas monstruosas y lidiar con sus propias habilidades vampíricas, su vida es un caos hilarante lleno de diálogos ingeniosos y situaciones bizarras.",
        tituloVideo: "Opening - staple stable",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2NrZjZiZ3hhNzliZA==",
        trailer: "https://www.youtube.com/embed/X63_YYZjKxA?si=A2iys5fMm6nZncof",
        db: "https://anidb.net/anime/6327"
    },
    {
        nombre: "Satoru Fujinuma",
        anime: "Boku dake ga Inai Machi",
        imagen: "media/img/57.jpg",
        video: "https://v.animethemes.moe/BokuDakeGaInaiMachi-ED1.webm",
        url: "https://bokudakegainaimachi.fandom.com/wiki/Satoru_Fujinuma",
        descripcion: "El mangaka con el poder más incómodo del mundo. Entre fracasos laborales y salvar el día, su vida es un enredo temporal constante.",
        tituloVideo: "Ending - Sore wa Chiisana Hikari no You na",
        episodio: "https://uqload.to/embed-64yjnq1dymp9.html",
        trailer: "https://www.youtube.com/embed/TZzMOC-4k6M?si=2u9ZFP4zjV5xBHVz",
        db: "https://anidb.net/anime/11292"
    },
    {
        nombre: "Kotarou Tennouji",
        anime: "Rewrite",
        imagen: "media/img/58.jpg",
        video: "https://v.animethemes.moe/RewriteS2-OP2.webm",
        url: "https://rewrite.fandom.com/wiki/Kotarou_Tennouji",
        descripcion: "El estudiante con una habilidad para meterse en los líos más sobrenaturales. Con su poder de reescribir su propio destino, su vida es una mezcla de desastres y aventuras hilarantes.",
        tituloVideo: "Opening - Last Desire",
        episodio: "https://uqload.to/embed-acljj3rie4ex.html",
        trailer: "https://www.youtube.com/embed/zACG02alQO0?si=2XU9vT4KoGmO_W1f",
        db: "https://anidb.net/anime/11643"
    },
    {
        nombre: "Nishikata",
        anime: "Karakai Jouzu no Takagi-san",
        imagen: "media/img/59.jpg",
        video: "https://v.animethemes.moe/Takagi3-OP1-NCBD1080.webm",
        url: "https://karakai-jouzu-no-takagi-san.fandom.com/wiki/Nishikata",
        descripcion: "Un chico eternamente atormentado por las bromas de su compañera. Con su espíritu competitivo y sus planes que siempre fallan, intenta sin éxito tomar la delantera.",
        tituloVideo: "Opening - Iwanai kedo ne.",
        episodio: "https://uqload.to/embed-tvpvb9wh1193.html",
        trailer: "https://www.youtube.com/embed/g4VJra3sLMg?si=JozqgopuedckxXGt",
        db: "https://anidb.net/anime/13270"
    },
    {
        nombre: "Shinei Nouzen",
        anime: "86: Eighty Six",
        imagen: "media/img/60.jpg",
        video: "https://v.animethemes.moe/86S2-OP1-NCBD1080.webm",
        url: "https://86-eighty-six.fandom.com/wiki/Shinei_Nouzen",
        descripcion: "El líder taciturno con más agallas que palabras. Siempre al frente de la batalla y con un apodo genial, 'Undertaker', maneja su escuadrón y sus problemas con una mezcla de seriedad y un toque oscuro de humor.",
        tituloVideo: "Opening - Kyoukaisen",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2hubHMwejVzYXZsYg==",
        trailer: "https://www.youtube.com/embed/VSdS29SDvn4?si=ytsE70xVkY4rkWOW",
        db: "https://anidb.net/anime/15441"
    },
    {
        nombre: "Ataru Moroboshi",
        anime: "Urusei Yatsura",
        imagen: "media/img/61.jpg",
        video: "https://v.animethemes.moe/UruseiYatsura2022-OP1-NCBD1080.webm",
        url: "https://uruseiyatsura.fandom.com/wiki/Ataru_Moroboshi",
        descripcion: "El chico más desafortunado y ligón del universo. Con una suerte horrible y un ojo para las chicas, su vida se convierte en un caos cuando una alienígena se enamora de él.",
        tituloVideo: "Opening - Aiue feat. Minami, SAKURAmoti",
        episodio: "https://uqload.to/embed-1en8i4e758bm.html",
        trailer: "https://www.youtube.com/embed/LXlFsAI3sYQ?si=bUzppOq_26VKcp9l",
        db: "https://anidb.net/anime/17096"
    },
    {
        nombre: "Kiyotaka Ayanokōji",
        anime: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
        imagen: "media/img/62.png",
        video: "https://v.animethemes.moe/YoukosoZitsu-OP1-NCBD1080.webm",
        url: "https://you-zitsu.fandom.com/wiki/Kiyotaka_Ayanok%C5%8Dji",
        descripcion: "El genio más tranquilo y desapercibido de la escuela. Con una cara de póker impecable y un talento para evitar llamar la atención, resuelve problemas complejos mientras parece que solo está tomando una siesta.",
        tituloVideo: "Opening - Caste Room",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3FxMWJ2NjZ4NjFzMA==",
        trailer: "https://www.youtube.com/embed/iYsx6w5PNno?si=QlHRPM6H7WfzH1dW",
        db: "https://anidb.net/anime/13153"
    },
    {
        nombre: "Aquamarine Hoshino",
        anime: "[Oshi no Ko]",
        imagen: "media/img/63.jpg",
        video: "https://v.animethemes.moe/OshiNoKo-ED1v2-NCBD1080.webm",
        url: "https://oshinoko.fandom.com/wiki/Aqua_Hoshino",
        descripcion: "El chico con más secretos y talento dramático que una telenovela. Con su habilidad para actuar y su afán de proteger a su familia, se convierte en un detective improvisado en el mundo del espectáculo.",
        tituloVideo: "Ending - Mephisto",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzQ3NG9zNjNjd3Yybg==",
        trailer: "https://www.youtube.com/embed/gKWEUJ4r5do?si=zqAPIQ55SnRCLbWT",
        db: "https://anidb.net/anime/17449"
    },
    {
        nombre: "Bell Cranel",
        anime: "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
        imagen: "media/img/64.jpeg",
        video: "https://v.animethemes.moe/DanMachi-OP1.webm",
        url: "https://danmachi.fandom.com/wiki/Bell_Cranel",
        descripcion: "El aventurero más optimista y desafortunado de la mazmorra. Con su habilidad para atraer problemas y monstruos por igual, su vida es una mezcla de heroísmo accidental y escenas cómicas.",
        tituloVideo: "Opening - Hey World",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzFweDNhNDB2amtocw==",
        trailer: "https://www.youtube.com/embed/sbcwRt0y4kY?si=kpE_tn8VdmFquU4J",
        db: "https://anidb.net/anime/10894"
    },
    {
        nombre: "Fushi",
        anime: "Fumetsu no Anata e",
        imagen: "media/img/65.jpg",
        video: "https://v.animethemes.moe/FumetsuNoAnataE-OP1.webm",
        url: "https://fumetsunoanatae.fandom.com/wiki/Fushi#",
        descripcion: "El ser más perdido y polifacético del universo. Con su habilidad para transformarse en cualquier cosa y su curiosidad ingenua, su vida es una aventura cómica de descubrimiento y confusiones.",
        tituloVideo: "Opening - PINK BLOOD",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9zdHJlYW10YXBlLmNvbS9lL1pYNkpROFBPdmpUcVZRcS9mdW1ldHN1MS5tcDQ",
        trailer: "https://www.youtube.com/embed/WHq46obaDR8?si=u_ZujpZtQ9nvNPcH",
        db: "https://anidb.net/anime/15351"
    },
    {
        nombre: "Shadow",
        anime: "Kage no Jitsuryokusha ni Naritakute!",
        imagen: "media/img/70.jpg",
        video: "https://v.animethemes.moe/ShadowGarden-OP1v4-NCBD1080.webm",
        url: "https://the-eminence-in-shadow.fandom.com/wiki/Cid_Kagenou",
        descripcion: "El maestro de las sombras con grandes sueños y una imaginación desbordante. Siempre está un paso adelante, o al menos eso cree él, mientras improvisa planes como si estuviera en un juego de rol.",
        tituloVideo: "Opening - HIGHEST",
        episodio: "https://uqload.to/embed-67mz7t0g8jwx.html",
        trailer: "https://www.youtube.com/embed/L7LgAbGF-WY?si=O1veuoLyBHlpxhzN",
        db: "https://anidb.net/anime/16073"
    },
    {
        nombre: "Ryu Yamada",
        anime: "Yamada-kun to Nananin no Majo",
        imagen: "media/img/73.jpg",
        video: "https://v.animethemes.moe/YamadaKun-OP1.webm",
        url: "https://nananinnomajo.fandom.com/wiki/Ryu_Yamada",
        descripcion: "El chico rebelde que parece tener un imán para los problemas y un talento especial para caer por las escaleras. Siempre está listo para un enredo divertido y un poco de caos mágico.",
        tituloVideo: "Opening - Kuchizuke Diamond",
        episodio: "https://uqload.to/embed-r5kw1ujs49z7.html",
        trailer: "https://www.youtube.com/embed/vDOknfJIUu4?si=Ff-Z4_fXpCnLkiR_",
        db: "https://anidb.net/anime/10955"
    },
    {
        nombre: "Bondrewd",
        anime: "Made in Abyss",
        imagen: "media/img/74.jpg",
        video: "https://v.animethemes.moe/MadeInAbyssMovie-ED1.webm",
        url: "https://madeinabyss.fandom.com/wiki/Bondrewd",
        descripcion: "Un villano con estilo, siempre con su casco brillante y su actitud calmada. Es un científico loco, famoso por sus experimentos inquietantes y su capacidad de mantener la compostura, sin importar lo macabro de la situación.",
        tituloVideo: "Ending - FOREVER LOST",
        episodio: "https://uqload.to/embed-wfqjkgc1omqt.html",
        trailer: "https://www.youtube.com/embed/AQbaZeby2zA?si=sZcU7mLDvREjk8si",
        db: "https://anidb.net/anime/12681"
    },
    {
        nombre: "Reinhard van Astrea",
        anime: "Re:Zero kara Hajimeru Isekai Seikatsu",
        imagen: "media/img/76.jpg",
        video: "https://v.animethemes.moe/ReZeroS2-OP1-NCBD1080.webm",
        url: "https://rezero.fandom.com/wiki/Reinhard_van_Astrea",
        descripcion: "Guapo, caballeroso y con más habilidades especiales que un videojuego con trucos. Siempre llega justo a tiempo para salvar el día y, si fuera un pastel, sería uno imposible de superar.",
        tituloVideo: "Opening - Realize",
        episodio: "https://uqload.to/embed-0pbqlenlretw.html",
        trailer: "https://www.youtube.com/embed/Slz_rahWp6Y?si=00omRhwhcmPCpT7E",
        db: "https://anidb.net/anime/11370"
    },
    {
        nombre: "Stark",
        anime: "Sousou no Frieren",
        imagen: "media/img/79.jpg",
        video: "https://v.animethemes.moe/SousouNoFrieren-OP2.webm",
        url: "https://frieren.fandom.com/wiki/Stark",
        descripcion: "Un guerrero tímido con la fuerza de un oso y la timidez de un gatito. Prefiere evitar ser el centro de atención, pero cuando la situación lo exige, se convierte en un verdadero titán en batalla.",
        tituloVideo: "Opening - Haru",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL3Y2MzBvcmRoY2VhOQ==",
        trailer: "https://www.youtube.com/embed/qgQunxD0qCk?si=aq7CJ5LI4Xk7oU_y",
        db: "https://anidb.net/anime/17617"
    },
    {
        nombre: "Muzan Kibutsuji",
        anime: "Kimetsu no Yaiba",
        imagen: "media/img/80.jpg",
        video: "https://v.animethemes.moe/KimetsuNoYaiba-OP1-NCBD1080.webm",
        url: "https://kimetsu-no-yaiba.fandom.com/wiki/Muzan_Kibutsuji",
        descripcion: "Un Michael Jackson demoníaco con complejo de Drácula. Siempre elegante y misterioso, prefiere transformar humanos en demonios en lugar de hacer amigos.",
        tituloVideo: "Opening - Gurenge",
        episodio: "https://uqload.to/embed-r3xsdxr53v7g.html",
        trailer: "https://www.youtube.com/embed/6vMuWuWlW4I?si=e-cAh8qSGOlwQDs5",
        db: "https://anidb.net/anime/14107"
    },
    {
        nombre: "Naofumi Iwatani",
        anime: "Tate no Yuusha no Nariagari",
        imagen: "media/img/83.jpg",
        video: "https://v.animethemes.moe/ShieldHero-OP2-NCBD1080.webm",
        url: "https://shield-hero.fandom.com/wiki/Naofumi_Iwatani",
        descripcion: "El héroe del escudo con la suerte más mala y el corazón más grande. Aunque empezó como el tipo más odiado del reino, demostró que la defensa es la mejor ofensa.",
        tituloVideo: "Opening - FAITH",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzQ3N21ncHB0YTZsZw==",
        trailer: "https://www.youtube.com/embed/VKYmpq-V3Rs?si=juZWOS-NbcSI6LYF",
        db: "https://anidb.net/anime/13246"
    },
    {
        nombre: "Kirigaya Kazuto",
        anime: "Sword Art Online",
        imagen: "media/img/90.jpg",
        video: "https://v.animethemes.moe/SwordArtOnline-OP1.webm",
        url: "https://swordartonline.fandom.com/wiki/Kirigaya_Kazuto",
        descripcion: "El espadachín prodigio con un talento para los videojuegos y un corazón de oro. Siempre vestido de negro, es el héroe solitario que acaba formando un harem virtual.",
        tituloVideo: "Opening - crossing field",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL250MXVobTBkMWg0eg==",
        trailer: "https://www.youtube.com/embed/aPP_Ut9Wqlg?si=ZGiQPnYb412uekRX",
        db: "https://anidb.net/anime/8692"
    },
    {
        nombre: "Yuji Itadori",
        anime: "Jujutsu Kaisen",
        imagen: "media/img/91.png",
        video: "https://v.animethemes.moe/JujutsuKaisen-ED1-NCBD1080.webm",
        url: "https://jujutsu-kaisen.fandom.com/wiki/Yuji_Itadori",
        descripcion: "El chico buena onda con la fuerza de un superhéroe y el estómago de acero. Se come un dedo maldito y termina compartiendo cuerpo con un demonio.",
        tituloVideo: "Ending - LOST IN PARADISE feat. AKLO",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2l0MDJjMjJibDRpNQ==",
        trailer: "https://www.youtube.com/embed/pkKu9hLT-t8?si=FMvm3zYo_-BT0KxC",
        db: "https://anidb.net/anime/15275"
    },
    {
        nombre: "Satoru Gojo",
        anime: "Jujutsu Kaisen",
        imagen: "media/img/92.jpg",
        video: "https://v.animethemes.moe/JujutsuKaisenS2-OP1-NCBD1080.webm",
        url: "https://jujutsu-kaisen.fandom.com/wiki/Satoru_Gojo",
        descripcion: "El maestro de jujutsu más fuerte y carismático, con ojos que podrían matar (literalmente) y un sentido del humor travieso. Siempre listo para una pelea y una broma.",
        tituloVideo: "Opening - Ao no Sumika",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2l0MDJjMjJibDRpNQ==",
        trailer: "https://www.youtube.com/embed/pkKu9hLT-t8?si=FMvm3zYo_-BT0KxC",
        db: "https://anidb.net/anime/15275"
    },
    {
        nombre: "Sukuna",
        anime: "Jujutsu Kaisen",
        imagen: "media/img/93.webp",
        video: "https://v.animethemes.moe/JujutsuKaisen-OP1-NCBD1080.webm",
        url: "https://jujutsu-kaisen.fandom.com/wiki/Sukuna",
        descripcion: "El rey de las maldiciones y el peor compañero de cuarto que podrías tener. Poderoso, malévolo y con un ego del tamaño de su maldad.",
        tituloVideo: "Opening - Kaikai Kitan",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2l0MDJjMjJibDRpNQ==",
        trailer: "https://www.youtube.com/embed/pkKu9hLT-t8?si=FMvm3zYo_-BT0KxC",
        db: "https://anidb.net/anime/15275"
    },
    {
        nombre: "Wakana Gojo",
        anime: "Sono Bisque Doll wa Koi o Suru",
        imagen: "media/img/96.jpg",
        video: "https://v.animethemes.moe/BisqueDoll-ED1-NCBD1080.webm",
        url: "https://sono-bisque-doll-wa-koi-wo-suru.fandom.com/wiki/Wakana_Gojo",
        descripcion: "El tímido y talentoso artesano de muñecas, con un don para la costura y un amor por el detalle. Aunque reservado, encuentra su chispa al colaborar con Marin en sus cosplays.",
        tituloVideo: "Ending - Koi no Yukue",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzI1bnJmcWFrb244eA==",
        trailer: "https://www.youtube.com/embed/8oveGY6h6T8?si=FCoyYgeU4R7PadM1",
        db: "https://anidb.net/anime/16250"
    },
    {
        nombre: "Aijou Rentarou",
        anime: "Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo",
        imagen: "media/img/98.webp",
        video: "https://v.animethemes.moe/Hyakkano-OP1.webm",
        url: "https://100kanojo.fandom.com/wiki/Aijou_Rentarou",
        descripcion: "El chico con el corazón más grande y el harem más grande. Con una dedicación infinita, se las arregla para ser el novio perfecto para 100 chicas.",
        tituloVideo: "Opening - Daidaidaidaidaisuki na Kimi e♡",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL29vNjdhODV1cG1oMA==",
        trailer: "https://www.youtube.com/embed/ls2VNcSifi4?si=953ZA7sDSmbQtoYs",
        db: "https://anidb.net/anime/17906"
    },
    {
        nombre: "Mash Burnedead",
        anime: "Mashle",
        imagen: "media/img/99.jpg",
        video: "https://v.animethemes.moe/MashleS2-OP1.webm",
        url: "https://mashle.fandom.com/wiki/Mash_Burnedead",
        descripcion: "El chico sin magia en un mundo mágico, pero con músculos que desafían la lógica. Resuelve problemas a puñetazos y come más crema que un pastel.",
        tituloVideo: "Opening - Bling-Bang-Bang-Born",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lLzVncjdwb21nNjhtOA==",
        trailer: "https://www.youtube.com/embed/zl0Kiv0kuQQ?si=PnMI78mP0S-g-x6j",
        db: "https://anidb.net/anime/17478"
    },
    {
        nombre: "Anos Voldigoad",
        anime: "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei Shite Shison-tachi no Gakkou e Kayou",
        imagen: "media/img/100.jpg",
        video: "https://v.animethemes.moe/MaouGakuinNoFutekigousha-OP1-NCBD1080.webm",
        url: "https://maou-gakuin.fandom.com/wiki/Anos_Voldigoad",
        descripcion: "El Rey Demonio reencarnado que puede vencer a cualquier enemigo con un chasquido. Arrogante pero encantador, siempre tiene una solución exageradamente poderosa para cada problema.",
        tituloVideo: "Opening - Seikai Fuseikai",
        episodio: "https://monoschinos2.com/reproductor?url=aHR0cHM6Ly9maWxlbW9vbi5zeC9lL2hidGhmMnFieDh3bQ==",
        trailer: "https://www.youtube.com/embed/9qJyDlZst8c?si=blb1RbjBl-vMX3Dv",
        db: "https://anidb.net/anime/15131"
    },
];

export { personajesMasculinos };